INSERT INTO Manufacturer (manufacturer_id, name) VALUES (1, 'MRF');
INSERT INTO Manufacturer (manufacturer_id, name) VALUES (2, 'Gabrial');
INSERT INTO Product (product_id ,name,description, manufacturer_id ,price) values (1,'Tyre Tube','Tyre Tube', 1, 1000);
INSERT INTO Product (product_id ,name,description, manufacturer_id ,price) values (2,'Tyre Radial','Tyre Radial', 1, 3000);
INSERT INTO Product (product_id ,name,description, manufacturer_id ,price) values (3,'Brake','Brake', 2, 4000);
INSERT INTO Product (product_id ,name,description, manufacturer_id ,price) values (4,'Tyre Tube','Tyre Tube', 1, 1000);
INSERT INTO Product (product_id ,name,description, manufacturer_id ,price) values (5,'Tyre Radial','Tyre Radial', 1, 3000);
INSERT INTO Product (product_id ,name,description, manufacturer_id ,price) values (6,'Brake','Brake', 2, 4000);
INSERT INTO Product (product_id ,name,description, manufacturer_id ,price) values (7,'Tyre Tube','Tyre Tube', 1, 1000);
INSERT INTO Product (product_id ,name,description, manufacturer_id ,price) values (8,'Tyre Radial','Tyre Radial', 1, 3000);
INSERT INTO Product (product_id ,name,description, manufacturer_id ,price) values (9,'Brake','Brake', 2, 4000);
INSERT INTO Product (product_id ,name,description, manufacturer_id ,price) values (10,'Tyre Tube','Tyre Tube', 1, 1000);
INSERT INTO Product (product_id ,name,description, manufacturer_id ,price) values (11,'Tyre Radial','Tyre Radial', 1, 3000);
INSERT INTO Product (product_id ,name,description, manufacturer_id ,price) values (12,'Brake','Brake', 2, 4000);
INSERT INTO Product (product_id ,name,description, manufacturer_id ,price) values (13,'Tyre Tube','Tyre Tube', 1, 1000);
INSERT INTO Product (product_id ,name,description, manufacturer_id ,price) values (14,'Tyre Radial','Tyre Radial', 1, 3000);
INSERT INTO Product (product_id ,name,description, manufacturer_id ,price) values (15,'Brake','Brake', 2, 4000);
INSERT INTO Product (product_id ,name,description, manufacturer_id ,price) values (16,'Tyre Tube','Tyre Tube', 1, 1000);
INSERT INTO Product (product_id ,name,description, manufacturer_id ,price) values (17,'Tyre Radial','Tyre Radial', 1, 3000);
INSERT INTO Product (product_id ,name,description, manufacturer_id ,price) values (18,'Brake','Brake', 2, 4000);
INSERT INTO Product (product_id ,name,description, manufacturer_id ,price) values (19,'Tyre Tube','Tyre Tube', 1, 1000);
INSERT INTO Product (product_id ,name,description, manufacturer_id ,price) values (20,'Tyre Radial','Tyre Radial', 1, 3000);
INSERT INTO Product (product_id ,name,description, manufacturer_id ,price) values (21,'Brake','Brake', 2, 4000);
INSERT INTO Product (product_id ,name,description, manufacturer_id ,price) values (22,'Tyre Tube','Tyre Tube', 1, 1000);
INSERT INTO Product (product_id ,name,description, manufacturer_id ,price) values (23,'Tyre Radial','Tyre Radial', 1, 3000);
INSERT INTO Product (product_id ,name,description, manufacturer_id ,price) values (24,'Brake','Brake', 2, 4000);
INSERT INTO Product (product_id ,name,description, manufacturer_id ,price) values (25,'Tyre Tube','Tyre Tube', 1, 1000);
INSERT INTO Product (product_id ,name,description, manufacturer_id ,price) values (26,'Tyre Radial','Tyre Radial', 1, 3000);
INSERT INTO Product (product_id ,name,description, manufacturer_id ,price) values (27,'Brake','Brake', 2, 4000);
INSERT INTO Product (product_id ,name,description, manufacturer_id ,price) values (28,'Tyre Tube','Tyre Tube', 1, 1000);
INSERT INTO Product (product_id ,name,description, manufacturer_id ,price) values (29,'Tyre Radial','Tyre Radial', 1, 3000);
INSERT INTO Product (product_id ,name,description, manufacturer_id ,price) values (30,'Brake','Brake', 2, 4000);
